"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from packaging.utils import _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a^a93&r70+jo%#b6dqwo!e!^4jgj#&9_(%m)!n$63w)fy7g44&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    "primetech.uz",
    "www.primetech.uz",
    "104.248.198.125",
]



# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # apps
    'users.apps.UsersConfig',
    'main.apps.MainConfig',
    # packages
    "django_ckeditor_5",
    'rest_framework',
    'drf_yasg',
    'rest_framework_simplejwt',
    "corsheaders",

]




UNFOLD = {
    "SITE_HEADER": "PrimeTech Admin",
    "SITE_URL": "https://primetech.uz",

    # Theme va rang sozlamalari
    "THEME": None,   # foydalanuvchi light/dark tanlay oladi
    "BORDER_RADIUS": "6px",

    # UI Builder sozlamalari
    "UI_BUILDER": {
        "enabled": True,
        "border_radius": True,
        "color_palette": True,
        "themes": ["light", "dark"],
    },

    # Recent actions (history) panelini yashirish
    "SHOW_HISTORY": False,
}



REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    )
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=90),
}

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
        }
    },
    'PERSIST_AUTH': True
}



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'


CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",   # frontend dev rejimi
    "http://104.248.198.125",  # agar frontend ham shu IP da ishlasa
    "https://primetech.uz",    # keyinchalik domen ulansa
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

CKEDITOR_5_CUSTOM_CSS = 'path/to/custom.css'  # optional

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'heading', '|',
            'fontSize', 'fontColor', 'fontBackgroundColor', '|',
            'bold', 'italic', 'link',
            'bulletedList', 'numberedList', 'todoList', '|',
            'codeBlock', 'emoji', '|',
            'undo', 'redo'
        ],
        'language': 'en',
        'fontSize': {
            'options': [8, 10, 12, 14, 16, 18, 24, 32, 48],
            'supportAllValues': True
        },
        'fontColor': {
            'colors': [
                {'color': '#000000', 'label': 'Black'},
                {'color': '#FF0000', 'label': 'Red'},
                {'color': '#00FF00', 'label': 'Green'},
                {'color': '#0000FF', 'label': 'Blue'},
                {'color': '#FFFF00', 'label': 'Yellow'},
                {'color': '#FFA500', 'label': 'Orange'},
                {'color': '#800080', 'label': 'Purple'}
            ],
            'columns': 5
        },
        'fontBackgroundColor': {
            'colors': [
                {'color': '#FFFFFF', 'label': 'White'},
                {'color': '#000000', 'label': 'Black'},
                {'color': '#FFEB3B', 'label': 'Light Yellow'},
                {'color': '#B3E5FC', 'label': 'Light Blue'},
                {'color': '#C8E6C9', 'label': 'Light Green'}
            ],
            'columns': 5
        }
    }
}




# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


import os

STATIC_ROOT = '/var/www/PRIMETECH/static/'
MEDIA_ROOT = '/var/www/PRIMETECH/media/'

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'users.User'
