# Generated by Django 5.2.5 on 2025-09-17 03:40

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='About title')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='description')),
                ('images', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='About images')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Announcement title')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcement/', verbose_name='Announcement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
        ),
    ]
