# Generated by Django 5.2.5 on 2025-09-17 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_about_announcement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='images',
            new_name='image',
        ),
        migrations.CreateModel(
            name='AboutImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='About image')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.about', verbose_name='About image')),
            ],
        ),
    ]
