# Generated by Django 5.2.5 on 2025-08-27 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_card'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='Cart',
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Cart', 'verbose_name_plural': 'Carts'},
        ),
    ]
