# Generated by Django 5.2.5 on 2025-09-17 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_images_about_image_aboutimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutImages',
            new_name='AboutImage',
        ),
    ]
