# Generated by Django 5.2.5 on 2025-09-17 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_aboutimages_aboutimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutimage',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.about'),
        ),
        migrations.AlterField(
            model_name='aboutimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about_images/', verbose_name='Image'),
        ),
    ]
